### ISSUE TITLE
Is there a way to add a watcher or participants to the task being created

### ISSUE THREAD

**Issue by berthor** [oktopuz/jira-bulk-loader#1]
Sometimes, I wish to add watchers to key tickets in a template, or participants when tickets get passed around to the same group of people to perform the required activities.  Is there a way to currently perform this activity within the template?

Thanks

**Comment by oktopuz** [comment]
Hi,

There is no way to set watchers at the moment.
If you have an idea about a good way to define the list of watchers for a ticket in the template, I think it can be implemented easily.

**Comment by berthor** [comment]
could we use something like this?
{"Watchers": [{"name": "A_person"},{"name": "A_person"},{"name": "A_person"}]}

**Comment by oktopuz** [comment]
Unfortunately it won't work that way.
I verified this using the following direct request to JIRA, and it returned an error.

```
$ curl -D- -u admin:admin -X POST --data '{ "fields": {"project": {"key": "JRA"}, "summary": "1st task", "priority": {"name": "Medium"}, "assignee": {"name": "admin"}, "watchers": [{"name": "admin"}], "issuetype": {"name": "Task"}}}'  -H "Content-Type: application/json"

http://localhost:2990/jira/rest/api/2/issue/
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
X-AREQUESTID: 1060x11956x1
X-ASEN: SEN
Set-Cookie: JSESSIONID=5392805C080165A1D5C87E2AFB3FB24F; Path=/jira/; HttpOnly
X-Seraph-LoginReason: OK
Set-Cookie: atlassian.xsrf.token=B7E3-Z04W-BS95-TT7E|59af0a79c8aa44ce08f0aa3b996302e5c00a50d4|lin; Path=/jira
X-ASESSIONID: 4res6v
X-AUSERNAME: admin
Cache-Control: no-cache, no-store, no-transform
X-Content-Type-Options: nosniff
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 30 Sep 2016 00:40:43 GMT
Connection: close

{"errorMessages":[],"errors":{"watchers":"Field 'watchers' cannot be set. It is not on the appropriate screen, or unknown."}}
```

Give me some time, I'll implement a workaround.

**Comment by berthor** [comment]
saw this post: https://answers.atlassian.com/questions/61770/please-help-got-error-400-when-trying-to-add-watcher-using-rest-api

Not sure if it is still applicable.

**Comment by oktopuz** [comment]
I've uploaded v0.3.1 with watchers support.
Their usernames has to be surrounded by '+'.

```
# summary *assignee1* +watcher1+ +watcher2+
```

Let me know If you see any problem.
